version: '3.5'
services:
  pgateway:
    build: .
    environment:
      DB_HOST: mongo
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
